---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ssv-exporter-2
  namespace: ssv
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: gp2
