---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ssv-node-paul-lh
  namespace: ssv
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: gp2
